name: Tu Shop CR
title: Documentación
author: Tu Shop CR
footer: Tu Shop CR

theme: jekyll-theme-cayman

# Site navigation links
- title: Home
  url: /

- title: Presentations
  url: /presentations/

- title: CV
  url: /cv/

- title: Blog
  url: /blog/

- title: Workshops
  url: /workshops/
